/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormularioFormSettingsShortIdRouteImport } from './routes/formulario.$formSettingsShortId'
import { Route as CChatIdRouteImport } from './routes/c.$chatId'
import { Route as ApiRepublishFormRouteImport } from './routes/api/republish-form'
import { Route as ApiPublishFormRouteImport } from './routes/api/publish-form'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCreateFormSubmissionFormSettingsShortIdRouteImport } from './routes/api/create-form-submission.$formSettingsShortId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularioFormSettingsShortIdRoute =
  FormularioFormSettingsShortIdRouteImport.update({
    id: '/formulario/$formSettingsShortId',
    path: '/formulario/$formSettingsShortId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CChatIdRoute = CChatIdRouteImport.update({
  id: '/c/$chatId',
  path: '/c/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRepublishFormRoute = ApiRepublishFormRouteImport.update({
  id: '/api/republish-form',
  path: '/api/republish-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublishFormRoute = ApiPublishFormRouteImport.update({
  id: '/api/publish-form',
  path: '/api/publish-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateFormSubmissionFormSettingsShortIdRoute =
  ApiCreateFormSubmissionFormSettingsShortIdRouteImport.update({
    id: '/api/create-form-submission/$formSettingsShortId',
    path: '/api/create-form-submission/$formSettingsShortId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-form': typeof ApiPublishFormRoute
  '/api/republish-form': typeof ApiRepublishFormRoute
  '/c/$chatId': typeof CChatIdRoute
  '/formulario/$formSettingsShortId': typeof FormularioFormSettingsShortIdRoute
  '/api/create-form-submission/$formSettingsShortId': typeof ApiCreateFormSubmissionFormSettingsShortIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-form': typeof ApiPublishFormRoute
  '/api/republish-form': typeof ApiRepublishFormRoute
  '/c/$chatId': typeof CChatIdRoute
  '/formulario/$formSettingsShortId': typeof FormularioFormSettingsShortIdRoute
  '/api/create-form-submission/$formSettingsShortId': typeof ApiCreateFormSubmissionFormSettingsShortIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/publish-form': typeof ApiPublishFormRoute
  '/api/republish-form': typeof ApiRepublishFormRoute
  '/c/$chatId': typeof CChatIdRoute
  '/formulario/$formSettingsShortId': typeof FormularioFormSettingsShortIdRoute
  '/api/create-form-submission/$formSettingsShortId': typeof ApiCreateFormSubmissionFormSettingsShortIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/publish-form'
    | '/api/republish-form'
    | '/c/$chatId'
    | '/formulario/$formSettingsShortId'
    | '/api/create-form-submission/$formSettingsShortId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/publish-form'
    | '/api/republish-form'
    | '/c/$chatId'
    | '/formulario/$formSettingsShortId'
    | '/api/create-form-submission/$formSettingsShortId'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/publish-form'
    | '/api/republish-form'
    | '/c/$chatId'
    | '/formulario/$formSettingsShortId'
    | '/api/create-form-submission/$formSettingsShortId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublishFormRoute: typeof ApiPublishFormRoute
  ApiRepublishFormRoute: typeof ApiRepublishFormRoute
  CChatIdRoute: typeof CChatIdRoute
  FormularioFormSettingsShortIdRoute: typeof FormularioFormSettingsShortIdRoute
  ApiCreateFormSubmissionFormSettingsShortIdRoute: typeof ApiCreateFormSubmissionFormSettingsShortIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulario/$formSettingsShortId': {
      id: '/formulario/$formSettingsShortId'
      path: '/formulario/$formSettingsShortId'
      fullPath: '/formulario/$formSettingsShortId'
      preLoaderRoute: typeof FormularioFormSettingsShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$chatId': {
      id: '/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/c/$chatId'
      preLoaderRoute: typeof CChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/republish-form': {
      id: '/api/republish-form'
      path: '/api/republish-form'
      fullPath: '/api/republish-form'
      preLoaderRoute: typeof ApiRepublishFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/publish-form': {
      id: '/api/publish-form'
      path: '/api/publish-form'
      fullPath: '/api/publish-form'
      preLoaderRoute: typeof ApiPublishFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-form-submission/$formSettingsShortId': {
      id: '/api/create-form-submission/$formSettingsShortId'
      path: '/api/create-form-submission/$formSettingsShortId'
      fullPath: '/api/create-form-submission/$formSettingsShortId'
      preLoaderRoute: typeof ApiCreateFormSubmissionFormSettingsShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublishFormRoute: ApiPublishFormRoute,
  ApiRepublishFormRoute: ApiRepublishFormRoute,
  CChatIdRoute: CChatIdRoute,
  FormularioFormSettingsShortIdRoute: FormularioFormSettingsShortIdRoute,
  ApiCreateFormSubmissionFormSettingsShortIdRoute:
    ApiCreateFormSubmissionFormSettingsShortIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
