/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CIndexRouteImport } from './routes/c/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const CIndexRoute = CIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/chat': typeof ApiChatRoute
  '/c': typeof CIndexRoute
}
export interface FileRoutesByTo {
  '/api/chat': typeof ApiChatRoute
  '/c': typeof CIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/chat': typeof ApiChatRoute
  '/c/': typeof CIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/chat' | '/c'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/chat' | '/c'
  id: '__root__' | '/api/chat' | '/c/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiChatRoute: typeof ApiChatRoute
  CIndexRoute: typeof CIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiChatRoute: ApiChatRoute,
  CIndexRoute: CIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
